@api = http://localhost:3156/sxw/usuarios

### GET COMPROBAR CORREO
GET {{api}}/verificar/?email=Hello@hsh.com
### POST ITEM
POST {{api}}/
Content-Type: application/json

{
    "usuario":"Legendario",
    "nombre":"Jesús Alberto Partida Michel",
    "email":"chuy492001@gmail.com",
    "contraseña":"Legendario156",
    "tipo":false
}